version: 2
jobs:
  build:
    docker:
      - image: vvakame/review
    steps:
      - checkout
      - run: npm i
      - run: rake clean lint pdf
      - store_artifacts:
          path: book.pdf
          destination: book.pdf